name: assign-automation
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: assign
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
